stages:
  data_ingestion:
    cmd: python src/RuralCreditPredictor/pipeline/data_ingestion.py
    deps:
      - src/RuralCreditPredictor/pipeline/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/RuralCreditData.zip
      - artifacts/data_ingestion/RuralCreditData.csv

  data_validation:
    cmd: python src/RuralCreditPredictor/pipeline/data_validation.py
    deps:
      - src/RuralCreditPredictor/pipeline/data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/RuralCreditData.csv
      - raw_schema.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_preprocessing:
    cmd: python src/RuralCreditPredictor/pipeline/data_preprocessing.py
    deps:
      - src/RuralCreditPredictor/pipeline/data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/RuralCreditData.csv
      - processed_schema.yaml
    outs:
      - artifacts/data_preprocessing/processed_data.csv

  data_transformation:
    cmd: python src/RuralCreditPredictor/pipeline/data_transformation.py
    deps:
      - src/RuralCreditPredictor/pipeline/data_transformation.py
      - config/config.yaml
      - artifacts/data_preprocessing/processed_data.csv
    outs:
      - artifacts/data_transformation/data_transformer.pkl

  model_training:
    cmd: python src/RuralCreditPredictor/pipeline/model_training.py
    deps:
      - src/RuralCreditPredictor/pipeline/model_training.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/model_training/latest_run_id.txt

  model_evaluation:
    cmd: python src/RuralCreditPredictor/pipeline/model_evaluation.py
    deps:
      - src/RuralCreditPredictor/pipeline/model_evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/model_training/latest_run_id.txt
      - artifacts/data_transformation/data_transformer.pkl
    outs:
      - artifacts/model_evaluation/test_metrics.txt
      - artifacts/model_evaluation/train_metrics.txt