independent_variables:
  Id: int64
  city: object
  age: int64
  sex: object
  social_class: object
  primary_business: object
  secondary_business: object
  annual_income: float
  monthly_expenses: float
  old_dependents: int64
  young_dependents: int64
  home_ownership: float64
  type_of_house: object
  occupants_count: int64
  house_area: float64
  sanitary_availability: float64
  water_availabity: float64
  loan_purpose: object
  loan_tenure: int64
  loan_installments: int64
  loan_amount: float64

target_variable:
  name: loan_amount
