root:
  artifact: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/heydido/datasets/raw/main/RuralCreditData.zip
  data_file: artifacts/data_ingestion/RuralCreditData.zip
  unzip_dir: artifacts/data_ingestion
  raw_file: artifacts/data_ingestion/RuralCreditData.csv

data_validation:
  root_dir: artifacts/data_validation
  raw_file: artifacts/data_ingestion/RuralCreditData.csv
  status_file: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  raw_file: artifacts/data_ingestion/RuralCreditData.csv
  preprocessed_file: artifacts/data_preprocessing/processed_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_file: artifacts/data_preprocessing/processed_data.csv
  data_transformer: artifacts/data_transformation/data_transformer.pkl

model_training:
  root_dir: artifacts/model_training
  preprocessed_file: artifacts/data_preprocessing/processed_data.csv
  train_metrics: artifacts/model_training/train_metrics.txt
  test_metrics: artifacts/model_training/test_metrics.txt
  model: artifacts/model_training/model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  model: artifacts/model_training/model.pkl
  train_metrics: artifacts/model_evaluation/train_metrics.txt
  test_metrics: artifacts/model_evaluation/test_metrics.txt

prediction:
  root_dir: artifacts/prediction
  data_transformer: artifacts/data_transformation/data_transformer.pkl
  model: artifacts/model_training/model.pkl
