root:
  artifact: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/heydido/datasets/raw/main/RuralCreditData.zip
  data_file: artifacts/data_ingestion/RuralCreditData.zip
  unzip_dir: artifacts/data_ingestion
  raw_file: artifacts/data_ingestion/RuralCreditData.csv

data_validation:
  root_dir: artifacts/data_validation
  raw_file: artifacts/data_ingestion/RuralCreditData.csv
  status_file: artifacts/data_validation/status.txt

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  raw_file: artifacts/data_ingestion/RuralCreditData.csv
  preprocessed_file: artifacts/data_preprocessing/processed_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessed_file: artifacts/data_preprocessing/processed_data.csv
  data_transformer: artifacts/data_transformation/data_transformer.pkl
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv
